project:
  type: website

website:
  title: "Chris Hughes"
  favicon: profile.jpg
  navbar:
    menu: false
    title: "Chris Hughes"
format:
  html:
    theme:
      light: [default, theme.scss]
      dark: [default, theme-dark.scss]
    css: styles.css

resources:
  - CNAME
  - collapsible.js



